In [2]:
import os
import json
import pickle
import numpy as np
import seaborn as sns
from tqdm import tqdm
import pandas as pd
# from dance_evaluation import *
import matplotlib.pyplot as plt
# from calculate_score import *
from collections import defaultdict
from utils.eval import *

In [55]:
a = 60; b= 140
mode = "zero_uni"
w_sec = 5; h_sec = w_sec/2
tolerance=0.13

# def estimate_tempo_posvel(a, b, mode, w_sec, h_sec, tolerance=0.13):
# Using both zero velocity and peak velocity
segment_pairs = [
    ("both_hand_x", "both_foot_x"),                     # Example: bpm_pos ~35%, bpm_posvel ~55%
    ("both_hand_y", "both_foot_y"),                     # Example: bpm_pos ~70%, bpm_posvel ~81%
    ("both_hand_resultant", "both_foot_resultant"),     # Example: bpm_pos ~49%, bpm_posvel ~66%

]

score_data = {}
json_data = {}
oPath = f"./saved_result/tempo_{a}_{b}/"


bpm_dict = ["bpm_median"]
for bpm_mode in bpm_dict:
    score_data[bpm_mode] = {}
    json_data[bpm_mode] = {}
    for hnd, ft in segment_pairs:
        # Build file paths for position and velocity data
        read_file1 = oPath + f"pos/{hnd}_{mode}_W{w_sec}_H{h_sec}_{a}_{b}.pkl"
        read_file2 = oPath + f"pos/{ft}_{mode}_W{w_sec}_H{h_sec}_{a}_{b}.pkl"
        read_file5 = oPath + f"pos/torso_y_{mode}_W{w_sec}_H{h_sec}_{a}_{b}.pkl"   # for reference tempo
        
        # Load the dataframes
        df1 = pd.read_pickle(read_file1)
        df2 = pd.read_pickle(read_file2)

        df5 = pd.read_pickle(read_file5)   # for reference tempo
        
        # Build candidate BPM pairs (for positions) and quads (for positions and velocities)
        global_tempo = []
        for n in range(df1.shape[0]):
            bpm_window1 = df1.iloc[n]["estimated_bpm_per_window"]   # hand (position)
            bpm_window2 = df2.iloc[n]["estimated_bpm_per_window"]   # foot (position)
            bpm_window3 = df5.iloc[n]["estimated_bpm_per_window"]   # torso (position) - not used here
            
            rbpm = df5.iloc[n]["music_tempo"]
            merged = np.stack((bpm_window1, bpm_window2, bpm_window3))
            print(rbpm)
            print(merged)
            if n == 5:
                break

        
        # ref = df1["music_tempo"].to_numpy()
        # accuracy, hit_idx, ref_hit_bpm = compute_dts(ref, global_tempo,
        #                                 tau=0.13, mode="one")

        
   


110
[[ 68 110 110 119]
 [139  60 135 126]
 [111 109 111 115]]
135
[[ 88 102 105]
 [128 136 103]
 [132 135 136]]
100
[[ 97  79  76  80]
 [139 139 101 128]
 [123 105  60 113]]
110
[[ 93 103  95 134]
 [134  81 133  92]
 [113 112 137 105]]
110
[[105  60 113 107]
 [134 120 103 139]
 [ 60  60  66  60]]
135
[[118 135 136]
 [139 102 103]
 [ 60  68  68]]
110
[[110 110 111 110]
 [104 107 114 117]
 [111 109 111 115]]
135
[[139 136 135]
 [139 137 139]
 [132 135 136]]
100
[[ 99 132 126  76]
 [104 116 139 101]
 [123 105  60 113]]
110
[[ 93 113 106  98]
 [139 111 114 139]
 [113 112 137 105]]
110
[[ 60  73  64  90]
 [134  87 139 139]
 [ 60  60  66  60]]
135
[[133 135 137]
 [139 135 134]
 [ 60  68  68]]
110
[[124 107 116 113]
 [ 60  60 106 105]
 [111 109 111 115]]
135
[[139 104 132]
 [ 60 123 138]
 [132 135 136]]
100
[[109 139 139 139]
 [120 139 139 117]
 [123 105  60 113]]
110
[[139 139 100 139]
 [ 71  77 102  70]
 [113 112 137 105]]
110
[[108  64 128 107]
 [139 126 130 129]
 [ 60  60  66  60]]
135
[[

In [ ]:
from scipy import stats
merged = np.stack((bpm_window1, bpm_window2, bpm_window3))
print(rbpm)
print(merged)



135
[[106 109 116]
 [ 99 100 132]
 [ 60  68  68]]


ModeResult(mode=array([60, 68, 68]), count=array([1, 1, 1]))